variables:
  PROJECT_NAME: hitsfood
  PROJECT_DIR: /opt/$PROJECT_NAME

include:
  - '.gitlab-ci-template.yml'

lint:
  extends:
    - .build-rules
  image: beevelop/sonarlint:latest
  stage: lint
  script:
    - echo "Running linter..."
    - sonarlint --html-report report/sonar.html
    - echo "Linter completed!"
  artifacts:
    paths:
      - report/sonar.html
    expire_in: 1 week
  tags:
    - docker

build:
  extends: 
    - .dotnet
    - .build-rules
  stage: build
  script:
    - echo "Running build..."
    - dotnet restore
    - dotnet build -c Release
    - dotnet publish -c Release
    - echo "Build completed!"
  artifacts:
    paths:
      - bin/*
    expire_in: 1 week
  needs: []

test:
  extends:
    - .dotnet
    - .build-rules
  stage: test
  script:
    - echo "Running test..."
    - dotnet test"
    - echo "Test completed!"

deploy:
  extends:
    - .deploy-rules
  stage: deploy
  script:
    - echo "Copy project to $PROJECT_DIR"
    - sudo cp -r . $PROJECT_DIR
    - cd $PROJECT_DIR
    - echo "Building docker-compose for deploy..."
    - sudo docker compose build
    - echo "Running docker-compose application..."
    - sudo docker compose -p $PROJECT_NAME up -d
    - echo "Application launched!"
  environment: staging
  when: manual
  tags:
    - deploy
