variables:
  PROJECT_NAME: hitsfood
  PROJECT_DIR: /opt/$PROJECT_NAME

lint:
  image: beevelop/sonarlint:latest
  stage: lint
  script:
    - echo "Running linter..."
    - sonarlint --html-report report/sonar.html
    - echo "Linter completed!"
  artifacts:
    paths:
      - report/sonar.html
    expire_in: 1 week
    rules: !reference [.build-rules, rules]
  tags:
    - docker

build:
  extends: .dotnet
  stage: build
  script:
    - echo "Running build..."
    - dotnet restore
    - dotnet build -c Release
    - dotnet publish -c Release
    - echo "Build completed!"
  artifacts:
    paths:
      - bin/*
    expire_in: 1 week
  rules: !reference [.build-rules, rules]
  needs: []

test:
  extends: .dotnet
  stage: test
  script:
    - echo "Running test..."
    - dotnet test"
    - echo "Test completed!"
  rules: !reference [.build-rules, rules]

deploy:
  stage: deploy
  script:
    - echo "Copy project to $PROJECT_DIR"
    - sudo cp -r . $PROJECT_DIR
    - cd $PROJECT_DIR
    - echo "Building docker-compose for deploy..."
    - sudo docker compose build
    - echo "Running docker-compose application..."
    - sudo docker compose -p $PROJECT_NAME up -d
    - echo "Application launched!"
  environment: staging
  when: manual
  rules: !reference [.deploy-rules, rules]
  tags:
    - deploy
