version: '3.3'

services:
  web:
    build: .
    ports:
      - "10000:80"
    links:
      - database
      - redis
    depends_on:
      - database
      - redis
    environment:
      # Чтобы работал Swagger на сервере, для фронтендеров
      ASPNETCORE_ENVIRONMENT: Development
    restart: always
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: food_delivery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: redis